### ISSUE TITLE
dá se pak název změnit?

### ISSUE THREAD

**Issue by nov51** [jklusacek73/RizeniSWProjektu#1]
Tak ať taky začneme nějakou komunikaci :D

Přidal jsem tabulky pro uživatele a soubory, k tomu i nějakej vysvětlující koment.

Byla to dřina... ten github desktop to nedělá o nic jednodužší.

V phpmyadmin si normálně kliknete na "Import", vybrat soubor a OK.

**Comment by jklusacek73** [comment]
jj díky
