### ISSUE TITLE
Nahrávání souborů do DB

### ISSUE THREAD

**Issue by nov51** [jklusacek73/RizeniSWProjektu#2]
Ty vole ty ses teda rozjel v tom SeeNowDo :D

Vsiml jsem si, ze jeden z tech ukolu je o nahravani souboru do db.

Urcite se daj ulozit do db, byly by to jenom pdfka, ne moc velky.

Tabulku pro uzivatele a soubory uz jsem vytvoril tak ze by obsahovali jen odkazy na soubory, ktery by se nachazeli na serveru, mozna by to rovnou vyresilo tenhle SND ukol

**Comment by nov51** [comment]
Čus, doufám, že si toho všimne někdo... zkoušel jsem nahrávání souborů a dostávám access denied - vypadá to, že upload není povolenej v php.ini

Je možný, že jsem někde udělal chybu, ale...
Pokud někdo má školu dneska, tak se běžte zeptat Smrčky, nebo to udělám já ve středu.

**Comment by jklusacek73** [comment]
jj udělej to ty až budeš mít čas. V php.ini je to povolený to jsme s Honzou zkoušeli, tak nevím kde je problém ale chtělo by to vyřešit.

**Comment by jklusacek73** [comment]
Ptal jsem se dnes na PWA jak je to s nahráváním souborů a bylo mi řečeno že to jde, ale je potřeba správně nastavit práva pro zápis do složky, takže by to mělo jít. Kdyby jsi to byl ochotný otestovat, byl bych rád. Pak by jsi mohl začít připravovat formulář pro nahrávání článků, tabulka v databázi už je připravená a mohlo by to jít. Díky

**Comment by nov51** [comment]
Nojo vůbec mě nenapadlo, že si práva můžeme měnit sami...

Formulář mám, už umí nahrávat soubory, zatím neumí nahrávat do DB, na tom budu pracovat zítra, ale...

číslo časopisu --- zatím to mám jako input text, jak se bude vybírat?

A předpokládám že id uživatele se veme ze "sešny"?

**Comment by nov51** [comment]
Mám hotovo nahrávání a ukládání do DB. Hned ty soubory nahraju.

Zatím je to limitovaný na txt,doc,docx, pdf formáty, a používá to stejnou formu jako registrace.php

po submitu to zobrazí hnusnou stránku, to se taky pak změní

Mužete to zkusit tady: 
http://195.113.207.171/~novak51/_RST/nahrat_clanek.php
a pak se podívat jestli je to na serveru: http://195.113.207.171/~novak51/_RST/uploads/

Do databáze neuvidíte..

*ID uživatele se pak bude muset získat jinak, pro zatím je to 1
*Taky se musí vymyslet způsob jak vybírat číslo časopisu

*Abys to zprovoznil u sebe, je potřeba přes putty nastavit složce do který ukládáš chmod 777 nazev_slozky
*soubory normálně hoď tam kde máš zbytek stránky a vytvoř složku uploads (nebo to změň v kódu)
*a taky je potřeba změnit údaje pro připojení do db, v souboru upload.php
*ID uživatele je 1, pokud ho v databázi nemáš, tak to asi hodí chybu


!! BUG - Jde nahrát soubor na server, bez toho že by se uložil do DB, zatím nevím jak to spravit, tak to dodělám později

Je toho celkem hodně, pro tak trapnej úkol :D
